FROM nginx:latest

COPY ./tcp-forward-web.tar.gz /usr/share/nginx/html/
RUN tar xzf /usr/share/nginx/html/tcp-forward-web.tar.gz -C /usr/share/nginx/html/

COPY ./nginx.conf /etc/nginx/nginx.conf

ENV TERM linux

